<a href="https://colab.research.google.com/github/cicily19/Introduction-to-Numpy/blob/main/IntroductionToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Numpy

Open Source Library hat forms the standard of working with numerical data(Matrix, Vectors) and forms the underlying foundation for libraries like Pandas and Matplotlib

### Numpy Arrays
This is the main data structure in Numpy and it has the following properties:

1. Can only store a single data type
2. Can be one-dimensional or multi-dimensional
3. Fixed size: their elements can be modified but they are fixed size(cannot change the length)


In [1]:
import numpy as np

In [2]:
# converting a python list to a numpy array
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
print(type(sales))

<class 'list'>


In [3]:
sales_array = np.array(sales)
print(type(sales_array))

<class 'numpy.ndarray'>


In [4]:
# properties
# ndim: number of dimensions
# shape: rows and columns
# size: total number of elements
# dtype: Data Types within the array
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

1
(10,)
10
int64


In [5]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

2
(2, 5)
10
int64


## Numpy Array Creation
We use the following function:
1. np.ones()
2. np.zeros()
3. np.arange()
4. np.linespace()
5. np.array.reshape()


In [6]:
# ones: float by default
ones = np.ones(5)
ones.dtype


dtype('float64')

In [7]:
zeros = np.zeros(5, dtype=int)
zeros.dtype

dtype('int64')

In [11]:
# arange(start, stop, step)
np.arange(2, 10, 2).reshape(2, 2)


array([[2, 4],
       [6, 8]])

In [9]:
# linespace()
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [10]:
# linespace()
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Indexing and Slicing Numpy Arrays

In [12]:
counties = np.array(["nairobi", "kisumu", "kericho", "nakuru", "kilifi", "kiambu", "laikipia", "nyeri"])
counties_array = np.array(counties).reshape(2, 4)
counties_array

array([['nairobi', 'kisumu', 'kericho', 'nakuru'],
       ['kilifi', 'kiambu', 'laikipia', 'nyeri']], dtype='<U8')

In [13]:
kericho_county = counties_array[0, 2]
kericho_county

'kericho'

In [14]:
kilifi_county = counties_array[1, 0]
kilifi_county


'kilifi'

In [17]:
# access for all(:) the record, the first two columns
counties_array.shape
counties_array[:, :2]

array([['nairobi', 'kisumu'],
       ['kilifi', 'kiambu']], dtype='<U8')

In [18]:
# first record of all the columns
counties_array[0, :]

array(['nairobi', 'kisumu', 'kericho', 'nakuru'], dtype='<U8')

### Filtering Numpy Arrays(Conditions)

In [19]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [20]:
condition = sales_array != 0
sales_array[condition]

array([   5,  155,  518, 1827,  616,  317,  325])

In [21]:
# Filtering arrays with multiple conditions
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [22]:
(sales_array == 616) | (sales_array < 100)


array([[ True,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [23]:
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [24]:
condition = (sales_array == 616) | (sales_array < 100)
sales_array[condition]

array([  0,   5,   0,   0, 616])

In [25]:
# Filtering using where(condition, ifblock, elseblock) condition
sales_inventory = np.array([12, 18, 102, 0, 0])
sales_inventory

array([ 12,  18, 102,   0,   0])

In [26]:
# where
np.where(sales_inventory <=0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [27]:
# products array
products_array = np.array(["egg", "milk", "bread", "rice", "beans"])
products_array

array(['egg', 'milk', 'bread', 'rice', 'beans'], dtype='<U5')

In [28]:
np.where(sales_inventory <=0, "Out of Stock", products_array)

array(['egg', 'milk', 'bread', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

### Aggregation methods

1. sum()
2. mean()
3. max()
4. min()
5. std()
6. var()
7.
8.


In [29]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [30]:
total_sales = sales_array.sum()
total_sales

3763

In [31]:
sales_array.mean()


376.3

In [32]:
sales_array.max()


1827

In [33]:
sales_array.min()

0

In [34]:
sales_array.std()

529.1366647662965

In [35]:
sales_array.var()

279985.61

In [36]:
np.percentile(sales_array, [25, 75])

array([  1.25, 469.75])